export * from './Abouts';
export * from './CallToAction';
export * from './Footer';
export * from './Hero';
export * from './Mockups';
export * from './Stat';
export * from './Testimonials';
export * from './Title';
export * from './Header';
